# Generated by Django 4.0.6 on 2022-07-21 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_detail_image_detailimage_and_more'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItems',
            new_name='OrderItem',
        ),
        migrations.RenameModel(
            old_name='OrderItemsStatus',
            new_name='OrderItemStatus',
        ),
        migrations.RenameModel(
            old_name='OrdersStatus',
            new_name='OrderStatus',
        ),
    ]
