# Generated by Django 4.0.6 on 2022-07-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_orderitems_orderitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default=-1, max_length=400),
            preserve_default=False,
        ),
    ]
