# Generated by Django 4.0.6 on 2022-07-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.AddField(
            model_name='delivery',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
