# Generated by Django 4.0.6 on 2022-07-26 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_address_delivery_address'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='delivery',
            table='deliveries',
        ),
    ]
