# Generated by Django 4.0.5 on 2022-07-19 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Detail_image',
            new_name='DetailImage',
        ),
        migrations.RenameModel(
            old_name='Thumbnail_image',
            new_name='ThumbnailImage',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='type',
            new_name='types',
        ),
    ]
